title: Interdisciplinary Computational Biology Workshop 2025
description: BRAC University, Dhaka, Bangladesh
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  repository_url: https://github.com/compbiobd/compbiobd.github.io
  is_project_page: https://github.com/compbiobd/compbiobd.github.io