title: CompBio'25
description: Interdisciplinary Computational Biology Workshop 2025
venue: Brac University
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  is_project_page: github.com/compbiobd