title: CompBio 2025
description: Interdisciplinary Computational Biology workshop 2025
venue: TBD
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  is_project_page: github.com/compbiobd