title: Interdisciplinary Computational Biology'25
description: A 3-day workshop open to senior undergraduate and graduate students, researchers, and faculty. The workshop aims to encourage participants in interdisciplinary research.
venue: Brac University
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman